// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenderHack.Infrastructure.Persistence;

#nullable disable

namespace TenderHack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TenderHackDbContext))]
    [Migration("20260912074451_AddCaseConcurrencyToken")]
    partial class AddCaseConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenderHack.Domain.Cases.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionReason")
                        .HasColumnType("text")
                        .HasColumnName("completion_reason");

                    b.Property<string>("ConversationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<int>("ModerationWarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_warning_count");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution_status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("TenderHack.Domain.Feedback.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("CommentText")
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<string>("InformationQualityRating")
                        .HasColumnType("text")
                        .HasColumnName("information_quality_rating");

                    b.Property<bool?>("Solved")
                        .HasColumnType("boolean")
                        .HasColumnName("solved");

                    b.Property<string>("SpecialistRating")
                        .HasColumnType("text")
                        .HasColumnName("specialist_rating");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_feedback");

                    b.HasIndex("CaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_feedback_case_id");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("TenderHack.Infrastructure.Persistence.CaseEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int?>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_case_events");

                    b.HasIndex("CaseId", "Id")
                        .HasDatabaseName("ix_case_events_case_id_id");

                    b.ToTable("case_events", (string)null);
                });

            modelBuilder.Entity("TenderHack.Infrastructure.Persistence.IdempotencyKeyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_hash");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("OwnerId", "Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_keys_owner_id_scope_key");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("TenderHack.Infrastructure.Persistence.NotificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("IntegrationMode")
                        .HasColumnType("text")
                        .HasColumnName("integration_mode");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("OwnerId", "Id")
                        .HasDatabaseName("ix_notifications_owner_id_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TenderHack.Infrastructure.Persistence.OutboxMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("DeliveredAt")
                        .HasDatabaseName("ix_outbox_delivered_at");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("TenderHack.Domain.Cases.Case", b =>
                {
                    b.OwnsMany("TenderHack.Domain.Cases.Turn", "Turns", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("case_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("Decision")
                                .HasColumnType("text")
                                .HasColumnName("decision");

                            b1.Property<int>("Revision")
                                .HasColumnType("integer")
                                .HasColumnName("revision");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("pk_turns");

                            b1.HasIndex("CaseId")
                                .HasDatabaseName("ix_turns_case_id");

                            b1.ToTable("turns", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaseId")
                                .HasConstraintName("fk_turns_cases_case_id");
                        });

                    b.OwnsOne("TenderHack.Domain.Handoffs.Handoff", "Handoff", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("AcceptedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("accepted_at");

                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("case_id");

                            b1.Property<string>("ExternalCaseId")
                                .HasColumnType("text")
                                .HasColumnName("external_case_id");

                            b1.Property<string>("IntegrationMode")
                                .HasColumnType("text")
                                .HasColumnName("integration_mode");

                            b1.Property<long>("LastExternalRevision")
                                .HasColumnType("bigint")
                                .HasColumnName("last_external_revision");

                            b1.Property<bool>("Stale")
                                .HasColumnType("boolean")
                                .HasColumnName("stale");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.Property<string>("Terminal")
                                .HasColumnType("text")
                                .HasColumnName("terminal");

                            b1.HasKey("Id")
                                .HasName("pk_handoffs");

                            b1.HasIndex("CaseId")
                                .IsUnique()
                                .HasDatabaseName("ix_handoffs_case_id");

                            b1.ToTable("handoffs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaseId")
                                .HasConstraintName("fk_handoffs_cases_case_id");

                            b1.OwnsOne("TenderHack.Domain.Handoffs.AssignedSpecialist", "AssignedSpecialist", b2 =>
                                {
                                    b2.Property<Guid>("HandoffId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("DisplayName")
                                        .HasColumnType("text")
                                        .HasColumnName("specialist_display_name");

                                    b2.Property<string>("Ref")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("specialist_ref");

                                    b2.HasKey("HandoffId");

                                    b2.ToTable("handoffs");

                                    b2.WithOwner()
                                        .HasForeignKey("HandoffId")
                                        .HasConstraintName("fk_handoffs_handoffs_id");
                                });

                            b1.OwnsOne("TenderHack.Domain.Handoffs.HandoffStage", "Stage", b2 =>
                                {
                                    b2.Property<Guid>("HandoffId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("stage_code");

                                    b2.Property<string>("DisplayName")
                                        .HasColumnType("text")
                                        .HasColumnName("stage_display_name");

                                    b2.HasKey("HandoffId");

                                    b2.ToTable("handoffs");

                                    b2.WithOwner()
                                        .HasForeignKey("HandoffId")
                                        .HasConstraintName("fk_handoffs_handoffs_id");
                                });

                            b1.Navigation("AssignedSpecialist");

                            b1.Navigation("Stage");
                        });

                    b.Navigation("Handoff");

                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
